### ISSUE TITLE
Meetup #1

### ISSUE THREAD

**Issue by MoOx** [MoOx/react-toulouse#1]
@todo

Discuss

(opened following discussion on https://communautes-toulouse.slack.com/archives/C6V8X4AN5/p1512052418000503)

**Comment by antoinerousseau** [comment]
Perso je peux animer une petite conf (ou autre) sur React Native, car je pense que c'est un framework qui a du potentiel niveau business donc ça peut être utile à nos confrères toulousains de le connaître voire de se l'approprier.
Du coup je pensais faire : 
* What is React Native (presentation, pros/cons, current status/community)
* My feedback and how I used it in my project
* Advices on architecture, tooling, etc

Et idéalement avoir d'autres retours d'expérience d'autres développeurs ?

J'ai d'abord ouvert une proposition de conf [sur GDGToulouse](https://github.com/GDGToulouse/meetup-cfp/issues/46) mais on peut en fait l'organiser indépendamment ici comme proposé par @MoOx

**Comment by MoOx** [comment]
Y'a eu ça sur toulouse https://www.youtube.com/watch?v=zYjJi9-Kon4 c'est pas trop mal fait je trouve :)

Moi je pourrais faire une intro sur react et les concept. Pour un meetup 1 ça me parait la base :)

**Comment by antoinerousseau** [comment]
Oui on peut faire une première partir React et une 2ème partie RN, puisqu'en effet la philosophie de composants est la même

**Comment by antoinerousseau** [comment]
Et du coup on vise une intro grand public ou on vise plus technique ?

**Comment by MoOx** [comment]
Aucune idée, à voir. Faudrait arriver à prendre la température. Peut etre pour celui là faire "grand public" (dev tout horizon? vu que c'est des intros)

Evidemment si on fait react puis react-native, le 2e sera concentré sur la spécificité de RN (ios/android/whatever + APIs / components de base)

**Comment by xavcz** [comment]
👋, salut @antoinerousseau!

Je reprends le meetup React Toulouse avec dans l'idée de rassembler la communauté React / RN à Toulouse et de voir ce qu'il peut en sortir!

La première édition a lieu dans 10 jours, le 10 avril: https://www.meetup.com/fr-FR/ReactJS-React-Native-Toulouse/events/pbzlmpyxgbnb/

Tu serais toujours chaud de faire ton talk sur React Native? 😄

**Comment by antoinerousseau** [comment]
Salut @xavcz, ça fait court 10 jours mais pourquoi pas si j'arrive à trouver le temps de préparer ça :)

Pour le contenu, plutôt une intro/présentation de RN ou un truc plus en profondeur ? Le public sera tech ou général, et quelle sera son expérience sur RN tu penses ?

Et combien de temps ?

**Comment by xavcz** [comment]
Je trouve le plan que t'as proposé il y a quelques mois excellent! 

Je pense partir sur la même trame pour mon talk, bonnes pratiques pour dév ses composants en isolation avec [React Cosmos](https://github.com/react-cosmos/react-cosmos/) (~= Storybook):

1. 👋 Speaker: Pourquoi faire ça / utiliser ça ? 
➡️ _Public: qu'est-ce que ça va changer dans ma vie de développeur React ?_
2. 👨‍💻 Speaker: Retour d'expérience sur un projet / demo de code 
➡️ _Public: ah ouais, c'est cool en pratique_
3. 🤔 Speaker: Conseils et ouverture sur les questions du public 
➡️ _Public: ok, et si ... ?_

Je passerai avant toi, j'aurai déjà couvert les bases de React au cas où. 

Je sais pas encore à quel type de public sera présent pour ce premier meetup, je te tiens au jus là-dessus! 👍 J'imagine un public tech, utilisant déjà ou voulant utiliser React intéressé par en savoir plus.

Un format de 20min de talk + 10min de questions, ça te semble bon ? 

On vient pour partager notre passion et nos talks pourraient avoir pour but de faire passer au public un bon moment, de leur faire se poser des questions et d'inviter aux échanges ? On y va en mode détente et tech 💯

**Comment by antoinerousseau** [comment]
détente & tech en 20 min de talk, ça me va 😉

**Comment by MoOx** [comment]
Si jamais je peux faire un truc en fallback si @antoinerousseau n'a pas le temps, sur Phenomic + React (ou tout autre chose de plus introductif à React?) :)

**Comment by antoinerousseau** [comment]
d'ailleurs si ça dit à un expert comme @MoOx de m'aider à le faire ensemble ?

**Comment by antoinerousseau** [comment]
hello, quelqu'un aurait la vidéo du meetup ? :)

**Comment by xavczen** [comment]
Yeah! https://www.youtube.com/channel/UCcTrYHzB_36Mr0kXf78Kjzw
