### ISSUE TITLE
Retour d'expérience - Passer d’une application React mono-client à multi-client

### ISSUE THREAD

**Issue by gkueny** [MoOx/react-toulouse#13]
Je vous propose un talk qui parle de mon expérience sur la migration d'une application React à gros traffic "**monoclient**" afin de la rendre "**multiclient**".

J'aimerai aborder principalement la réflexion que l'on a eu sur cette problématique, la solution qui en est sortie et du pourquoi je pense que React est bien taillé pour une application multiclient.

Je pense que le talk ne devrai pas être trop long (10 à 20min ?) car le but n'est pas forcément de parler du code mais plus du comment/pourquoi et pouvoir parler ensuite ensemble des solutions alternatives.

Ça serai mon premier talk 😊

**Comment by MoOx** [comment]
Bonne idée. Je serais un bon relecteur pour ton talk si tu veux, j'ai vécu ça l'année dernière sur un projet d'envergure, qui a été pensé comme un produit puis décliné en marque blanche :)

**Comment by gkueny** [comment]
@MoOx Pour la relecture je suis preneur !

**Comment by MoOx** [comment]
Vu que ça serait ton premier talk, je te pose ça là ça peut tjrs servir http://speaking.io/ :)

**Comment by gkueny** [comment]
Merci @MoOx

**Comment by MoOx** [comment]
@gkueny tu as avancé sur ton sujet?

**Comment by gkueny** [comment]
J'ai pas du tout pris le temps de me poser dessus @MoOx,
J'ai la base et la structure en tête mais faut encore que je fasses mes slides / écrive plus précisément ce dont je vais parler

Je pense m'y mettre cette semaine / weekend

**Comment by MoOx** [comment]
No rush :)

**Comment by euZebe** [comment]
Salut ! Je viens aux nouvelles ; @gkueny, as-tu avancé sur la préparation ? Ce serait chouette de faire une session avant l'été.

**Comment by gkueny** [comment]
Hello @euZebe !

Je n'ai absolument pas avancé dessus :( 

J'ai cru comprendre que ça serait pour Juin ? (cf https://github.com/MoOx/react-toulouse/issues/7#issuecomment-489206366 )

Je peux préparer quelque chose pour cette date la

**Comment by euZebe** [comment]
"ce serait pour juin": disons que j'aimerais bien, avant l'été, si on a de la matière. Et avoir de nouveaux speakers n'est pas pour me déplaire :)

**Comment by MoOx** [comment]
Dans 15j tu serais prêt? Je veux lancer une nouvelle édition

**Comment by gkueny** [comment]
Yes

**Comment by MoOx** [comment]
Super. Je communique la date asap pour voir si t'es dispo :)

**Comment by MoOx** [comment]
Au programme du prochain https://www.meetup.com/ReactJS-React-Native-Toulouse/events/261825414/
