### ISSUE TITLE
React hooks - retours d'expérience

### ISSUE THREAD

**Issue by euZebe** [MoOx/react-toulouse#14]
La demande a été formulée sur [Slack](https://communautes-toulouse.slack.com) d'un retour d'expérience sur les hooks, au-delà des bêtes compteurs et todo apps, sur des applis significatives.

Entre projets from scratch écrits exclusivement avec des hooks, projets où les hooks se mélangent aux classes, et migration progressive, nous avons probablement des choses à présenter : avantages, inconvénients, points de vigilance, difficultés ou facilités pour se les approprier, trucs et astuces...

Dans un premier temps, il me semble opportun de présenter le fonctionnement des hooks, après quoi plusieurs personnes pourraient intervenir sur des formats courts (ou pas, comme chacun le sent) pour partager leur expérience et leurs conseils sur le sujet.

NB: Il serait chouette de faire cette prez courant novembre.

**Comment by euZebe** [comment]
en guise d'introduction, voici ce que j'avais en tête:

# Introduction aux Hooks

## règles fondamentales
hooks en début de fonction
hooks non conditionnés (pas de `if(...) { useEffect(...);}` par exemple)

## mise en pratique
### cycle de vie
- implem d'un composant React basique sous forme de fonction
- volonté d'ajouter un state + contrôler le cycle de vie => avant les hooks: 
transformation en classe (rappel sur le cycle de vie)
- how-to avec les hooks

### factoriser un comportement 
- avant les hooks: render prop ou HOC
- how-to avec les hooks

## tips
- différents types de hooks ? Faut-il balayer tous ou les principaux hooks ?
- custom hooks
- plugin eslint (en parler ? pas forcément, c'est de base dans CRA)
- possibilité de mixer hooks et classes
- `useState` vs `this.setState` (qui est plutôt un `mergeState`, techniquement)
- Bonne pratique: séparation des states avec les hooks

**Comment by ylastapis** [comment]
J'y voit aussi:
Cas d'usage des hooks avec Redux.
Cas d'usage des coins dans des formulaires complexes.
Factorisation de code réutilisable avec custom hooks et par exemple le fetch de données --> deuxième partie de la prez que tu mentionnais

**Comment by antoinerousseau** [comment]
Donc comme je disais je veux bien intervenir quelques minutes si besoin
en vrac, voici les trucs que j’aimerais raconter :
- une petite note sur le côté lisibilité discutable des hooks pour les débutants (moi j’adore les hooks mais faut bien admettre que componentDidMount est plus parlant qu’un useEffect avec un tableau vide), et surtout sur le fait qu’il faut pas forcément associer chaque ancienne méthode à un hook (penser useEffect différemment de didMount/etc, penser “effet” et ses dépendances, etc)
- retour d’xp (ranger ses hooks dans des hooks, les pièges, etc)
- parmi les pièges, j’aimerais parler des conséquences des closures sur la valeur retournée par un useState dans un event listener lui même défini dans un useEffect : la valeur étant “stale” (pas à jour), il est parfois nécessaire de faire appel à une ref
- peut être faire une mini intro de hooks externes populaires (useLocation, useStaticQuery, etc)
- typescript

**Comment by myagoo** [comment]
Je voudrais parler de tips & gotchas autour des hooks
useState avec fonction d'init,
useState qui ne supporte pas le second argument callback comme dans setState
useMemo qu'il ne faut utiliser QUE comme optim de perf
les useCase autour des refs
Pourquoi encore utiliser createRef
Faire des démos de composition de hooks

**Comment by myagoo** [comment]
Je voudrais parler de rules-of-hooks, pourquoi c'est bien, pourquoi il faut faire attention quand on l'introduit dans une codebase, pourquoi il faut pas toujours prendre pour argent comptant ce qu'il dit

**Comment by myagoo** [comment]
Aussi : https://lukaszmakuch.pl/post/react-hooks-oops-part-3-an-effect-does-not-run-again-when-its-dependencies-change/

**Comment by MoOx** [comment]
Euh là en gros il fait de l'écoute sur un champs sans "listener" (pas de `onChange`) et il voudrait que ça marche? Wtf un peu ce post

**Comment by myagoo** [comment]
oui, il utilise son compo en mode non controlé. Je sais bien que tu n'es pas la cible de ce post, mais il faut comprendre que des gens croient vraiment que les hooks sont magiques

**Comment by MoOx** [comment]
Non mais là c'est remettre en cause les bases de React... En mode non contrôlé justement tu décides explicitement  quand tu lis la valeur, et là... Enfin peut etre comme tu dis que les gens "imagines" des choses non explicite (mais bon clairement si RTFM on devrait pas s'imaginer ce genre de choses)

**Comment by mabhub** [comment]
Pour éviter cette confusion, une possibilité est de _comparer_ ce paramètre de `useEffect` à une clé de mémoïsation… Ou peut-être juste de rappeler que c'est une condition, et non un déclencheur de l'effet.

**Comment by myagoo** [comment]
> Non mais là c'est remettre en cause les bases de React... En mode non contrôlé justement tu décides explicitement quand tu lis la valeur, et là... Enfin peut etre comme tu dis que les gens "imaginent" des choses non explicite (mais bon clairement si RTFM on devrait pas s'imaginer ce genre de choses)

Je trouve son post légitime => la dépendance à changé, les newbies des hooks peuvent croire que cette dépendance est watchée dans les coulisses et que leur effect sera déclenché

**Comment by ylastapis** [comment]
Donc pour résumer

- Présenter les bases ~30min ? => @euZebe
- Connected Component (redux) => TS + FC + hooks ~15min => Nous. On peut déborder sur quand utiliser ou ne pas utiliser Redux.
- Tester efficacement les composants ~15min => ?
- Demo Ryan Florence ? ~15min => ?
- Factorisation des custom hooks + organisation ~15min => "Faire des démos de composition de hooks" @myagoo ?
- Tips & Gotchas sur les hooks ~15min => @myagoo également ?

Hadrien voulait pas présenter un truc également ?

**Comment by euZebe** [comment]
Effectivement je veux bien m'occuper de l'implémentation naïve des hooks.
et c'est Zélia qui devrait s'occuper de l'introduction.

**Comment by antoinerousseau** [comment]
Heu et du coup moi rien ? :/

**Comment by ylastapis** [comment]
@antoinerousseau my bad, j'ai zappé ton comment plus haut, désolé.
@MoOx oui j'essaie de synthétiser, qu'on bosse pas tous sur la même chose :)

**Comment by real34** [comment]
Si vous me dites ce que vous attendez pour les tests sur les hooks, je veux bien préparer des exemples pour faire 15 min sur le sujet.

Vous ne craignez pas que cela fasse trop d'orateurs  ?

**Comment by euZebe** [comment]
Sur les tests, je suis néanmoins de l'avis de @MoOx, qui a été discuté sur Slack il y a quelques semaines : des tests de composant ne devraient pas être différents selon l'implémentation.

Oui ça va faire beaucoup d'orateurs, mais l'idée des lighting talks me semble intéressante. On expérimente.
(et si tu as quelque chose qu'il te semble pertinent de présenter néanmoins, @real34, tu peux préparer un truc de 10-15 minutes max.

**Comment by real34** [comment]
En effet, rien de particulier lié aux hooks. Pas plus que pour les HOC à la belle époque quoi, ou autre depuis.

Ça m'arrange d'arriver les mains dans les poches sans avoir de présentation à faire :-)

**Comment by antoinerousseau** [comment]
Le plan : https://docs.google.com/document/d/1j5oieM_DgB4fyn7S47QMDW12WaOUDahyL5-KR4R8cqQ/edit

**Comment by MoOx** [comment]
Ton lien n'est pas public

**Comment by antoinerousseau** [comment]
Sorry, il faut demander l'accès à @ylastapis (ou sinon je l'enlève de l'issue)

**Comment by ylastapis** [comment]
done

**Comment by MoOx** [comment]
Les archives sont ici https://react-toulouse.js.org/meetup/6/
