### ISSUE TITLE
Gatsby

### ISSUE THREAD

**Issue by antoinerousseau** [MoOx/react-toulouse#15]
Je vous propose un petit talk :

- Présentation de la [JAMstack](https://jamstack.org/) et ce qu'elle apporte aux besoins actuels en dev Web
- Présentation de [Gatsby](https://www.gatsbyjs.org/), framework open source de génération de sites React statiques
- Retours d'expérience : je peux faire un retour mais s'il y en a d'autres ça serait top :)

**Comment by mabhub** [comment]
Si on est pas pressé, je peux envisager de faire plusieurs RXP…

*(Perso j'adore Gatsby, et je commence à avoir quelques petites prods)*

**Comment by euZebe** [comment]
On peut prévoir ça pour janvier ? Février ?

**Comment by antoinerousseau** [comment]
Oui on peut dire janvier :)
Qui choisit la date ? Et comment ? Et le lieu ?

**Comment by euZebe** [comment]
Comme on a assez peu de propositions de talk, je suis d'avis de ne pas trop les condenser.
Donc la date c'est arbitraire, en fonction de la dispo des speakers et du lieu.
Le lieu justement, c'est comme on veut. On avait déjà fait 2 sessions à Labège ; il se trouve qu'il y a pas mal de gens qui font du React là-bas. Mais on peut aussi viser le centre ville comme la dernière fois et celle à venir.
AtHome a l'air très disponible pour nous accueillir en tout cas, et gratuitement.

Reste enfin la question du sponsoring, mais on doit pouvoir trouver parmi nos contacts et clients.

**Comment by DirtyF** [comment]
Si c'est en Janvier, je pourrais _peut-être_ faire une présentation de https://tinacms.org basée sur https://github.com/tinacms/tina-starter-grande, le projet sera déjà un peu plus mature.

**Comment by antoinerousseau** [comment]
@DirtyF archi chaud ! ça a l'air chouette ce projet

**Comment by DirtyF** [comment]
@antoinerousseau cool, vu que je suis pas un grand technicien, ça sera surtout pour présenter les concepts, les possibilités actuelles (avec espérons-le d'ici là de nouveaux plugins pour Next.js et d'autres backend que Git) et à venir.

**Comment by antoinerousseau** [comment]
Petit sondage sur la date du meetup :
https://doodle.com/poll/8nbuwua9d6wwq8at

**Comment by misnard** [comment]
Hello, avec mes collègues de chez commit42 on bosse sur un side project sur lequel on pourrait faire un talk si vous voulez c'est un Gatsby + sylius, donc du e-commerce avec du Gatsby :)

**Comment by antoinerousseau** [comment]
@misnard carrément :)
est-ce que la ou les personnes qui veulent donner ce talk peuvent répondre au doodle, et les autres peuvent enlever leur réponse stp ?

**Comment by antoinerousseau** [comment]
Donc ce sera à Ô Local le 27 janvier !

**Comment by misnard** [comment]
Mathieu et moi avons répondu @antoinerousseau

**Comment by antoinerousseau** [comment]
@mabhub dispo pour faire un petit retour ?
@DirtyF dispo pour nous présenter TinaCMS ?

**Comment by mabhub** [comment]
> @mabhub dispo pour faire un petit retour ?

J'ai *rien* de prêt.
Je veux dire, je n'ai pour le moment aucune idée de comment structurer une présentation avec l’expérience que j'ai et les idées que j'ai en tête ^^'

En y réflechissant 5min, j'arrive à ça :
Dans les trucs qui peuvent être abordés _(sur lesquels je peux préparer qqch si qqn d'autre ne le fait pas déjà)_ :
- Le b.a.-ba de Gatsby sous forme d'une mini démo : Prendre un _starter_ minimaliste, le lancer, et expliquer l'anatomie *de base* _(les fichiers `gatsby-*.js` sans entrer trop dans les détails, les fichiers `src/pages/*.js` qui deviennent chacun une route/page)_, le _build_ généré complètement statique utilisable sans JS.
- Le mécanique général de Gatsby (les possibilités principales de `gatsby-node.js`) : Création de _nodes graphql_, création de _pages_ arbitraires, requêtes graphql pour les pages _(page queries)_ et dans les composants (static queries) et donc de  comment les données sont mises à dispo des pages et composants
- Les écueils principaux liés à la génération statique dans Gatsby : _« Si je monte un composant qui fait appel à besoin de window (ou de l'API du browser), ça casse tout »_
- Écrire un petit plugin Gatsby
- Les plugins Gatsby intéressants
- ...

Après, si quelqu'un qui a l'habitude d'organiser les idées ou la trame pour une prés', je suis preneur de toute l'aide possible.

En gros pour le moment, c'est juste une ébauche/idée de contenus potentiels, et j'ai besoin d'aide et avis pour structurer quelque chose qui convienne au gens qui viennent au meetup (et s'articule avec ce que proposent les autres)

**Comment by euZebe** [comment]
👌 @mabhub.
A moins que tu ais prévu de bosser le sujet pendant les vacances, on peut organiser une réunion avec les différents orateurs potentiels début janvier, pour définir le périmètre de chaque talk ; Partant de là tu pourras aviser sur que présenter.

**Comment by mabhub** [comment]
Ça me va ! :+1:

**Comment by antoinerousseau** [comment]
https://www.meetup.com/fr-FR/ReactJS-React-Native-Toulouse/events/267224842/

**Comment by misnard** [comment]
du coup @antoinerousseau pour la présentation de Gatsbylius c'est ok ?

**Comment by antoinerousseau** [comment]
@misnard bien sûr ! je propose qu'on se réunisse entre intervenants début janvier pour organiser le meetup si ça vous dit ? quelles sont vos dispos ? => https://doodle.com/poll/wxh7ixnrsdfw3qx8
cc @mabhub @DirtyF

**Comment by misnard** [comment]
@antoinerousseau Pas de soucis, possible de présenter le sujet a 2 ? :)

**Comment by antoinerousseau** [comment]
@misnard bien sûr !

**Comment by misnard** [comment]
Super ! :)

**Comment by antoinerousseau** [comment]
Donc pour ceux qui veulent intervenir, notez qu'on se voit le 14 janvier à 19h pour se mettre au point !
Ça marche aussi pour ceux qui ne se seraient pas encore manifestés ;)

**Comment by misnard** [comment]
Hey du coup @antoinerousseau on a toujours pas eu le lieux pour le 14 janvier :)

**Comment by antoinerousseau** [comment]
on peut faire ça chez moi ou chez Occitech si ça vous dit ?

**Comment by mabhub** [comment]
Si Occitech est toujours bvd des Récollets, moi ça m'arrange bien :D

**Comment by real34** [comment]
Oui, on est toujours Bvd des Récollets !

**Comment by antoinerousseau** [comment]
Pour les intervenants, RDV mardi soir (14 janvier) après le taf (19h) chez Occitech (35 B Boulevard des Récollets, et si mes souvenirs sont bons on peut entrer par la rue des Saules, en contrebas) pour préparer ce meetup :)

**Comment by DirtyF** [comment]
@antoinerousseau La version cloud de TinaCMS n'est pas encore dispo - l'intéret est donc encore trop limité à mon sens. Je remets donc ma proposition de présentation à plus tard, et dans l'idée Tina sera moins couplée à React, mais à des web components standards.

**Comment by MoOx** [comment]
Les archives sont ici https://react-toulouse.js.org/meetup/7/
