### ISSUE TITLE
Meetup #2

### ISSUE THREAD

**Issue by euZebe** [MoOx/react-toulouse#2]
Bonjour,

Pour le prochain meetup, je souhaite proposer un talk 'bonnes pratiques Redux". 
Quelqu'un aurait-il un autre sujet à présenter ?

Il paraît que vous utilisez Appolo Client chez Citymeo ; un retour serait très apprécié. :)

Concernant React Native, j'ai eu un retour d'une personne qui aurait aimé voir du code RN ; je lui expliqué que c'était en tout point similaire à du React, si ce n'est les `<View>` à la place des `<div>` ; néanmoins il serait peut-être bon de proposer un petit sujet pour montrer comment se passe concrètement le développement avec RN: 
* expliquer brièvement ce qui est nécessaire pour monter l'environnement de dev, 
* comment démarrer un projet (create-react-native-app), 
* montrer un minimum de code, 
* montrer qu'on peut débugger avec les chrome dev tools
* les particularités comme les stylesheets, et enfin finir par 
* packager une application minimaliste pour la mettre sur son device...

Ca vous paraît pertinent ? Si oui, qui est tenté ?

**Comment by MoOx** [comment]
Si ça vous dit je peux faire un équivalent de ça en prés pour RN http://putaindecode.io/fr/articles/js/react/native/introduction/ (en gros une app simple avec un fetch)

**Comment by MoOx** [comment]
Mais sinon j'avais un tête un "you might not need redux" aussi (peut etre une prochaine fois plus tôt)

**Comment by euZebe** [comment]
Je trouverais ça aussi très bien. J'ai demandé à ooflorent un retour d'expérience sur ce qu'ils ont fait à Overblog: ils ont dégagé Redux sur tout leur code pour utiliser seulement la nouvelle API de contexte.
Il n'est pas contre l'idée ; il faut qu'il arrive à se motiver pour préparer un sujet.

**Comment by MoOx** [comment]
Entre virer redux et utiliser l'api context, ca change rien (car redux utilise le context). Mon idée c'est plutôt que je vois trop de gens TOUT mettre dans redux, meme des choses qui n'ont pas lieu d'y être. En gros l'idée c'est rappeller que setState  marche très bien le plus souvent, et que redux/context c'est quand je suis bloqué avec setState (ou que mon code va sentir le sapin très fort).

**Comment by jibees** [comment]
@MoOx je serai preneur aussi d'une pres' sur reasonml si tu as de l'expérience en prod.

**Comment by MoOx** [comment]
Pas encore d'xp en prod sur un projet réelle mais ca va pas tarder :)

**Comment by euZebe** [comment]
@MoOx "Ca ne change rien"... j'aimerais bien un retour d'XP pour voir comment ils l'utilisent, justement. Parce que tu peux avoir plusieurs contextes, par exemple. 

Ta proposition me semble intéressante aussi. C'est un débat qui n'est pas tranché en termes de bonne ou mauvaise pratique, tout mettre dans le store redux, mais un avis est toujours bon à prendre :)

**Comment by JulienPradet** [comment]
@euZebe Par rapport à la suggestion de présentation de RN par du code, je trouverais ça intéressant aussi de voir comment ça fonctionne pour des composants qui ont besoin de code spécifique à la plateforme.

Exemple (pas forcément pertinent) : montrer comment faire une gallerie d'image. Il y aurait le code pour Android et iOS et ensuite le composant React qui homogénéise leur utilisation.

----

Sinon, je ne sais pas si c'est le bon endroit pour en parler, mais il y a plein de talks auxquels je viendrai assister avec plaisir :
* Retour d'expérience de Next.js : routing, animations, SEO, etc. Comment ça se passe ? Est-ce que c'est beaucoup de contraintes ou est-ce qu'il y a une solution à tout ?
* preact dans la vraie vie (sans react-compat notamment, pour savoir qu'est-ce que ça impose comme contraintes, si c'est très gênant au niveau de l'écosystème, etc.)
* React Async, s'il y en a qui ont déjà des aventuriers qui ont commencé à jouer avec
* Reason React
* Relay Modern
* Des talks sur les tests
* CSS in JS : avec des retours d'expérience sur certaines libs notamment
* Faire des animations en React :hand: 
* Storybook : la liste des addons indispensables :hand: 

Les talks avec les :hand: sont des talks que je pourrais donner si ça vous intéresse.

S'il y a besoin de retour d'expérience sur Apollo, on l'utilise aussi à Occitech pour Front-Commerce. Mais si des gens de Citymeo sont motivés, on laisse avec plaisir la place :)

**Comment by GillesDebunne** [comment]
@julien, je veux bien ta liste d'addons storybook. Je n'en trouve aucun de
vraiment pertinent.

Et pour contribuer à la discussion no-redux, j'ai fait un projet avec
Firebase dans lequel j'ai remplacé React par firebase

2018-04-17 13:11 GMT+02:00 Julien Pradet <notifications@github.com>:

**Comment by Liliatux** [comment]
Je suis motivée pour présenter soit Apollo Client, Next.js ou Flow.
Je pense effectivement que parmi les 3 sujets, Apollo Client est le plus pertinent pour la prochaine meetup au vu de son sujet sur redux, ça permettra de montrer les contrastes entre les deux.
@JulienPradet, on peut mettre en commun nos connaissances/compétences sur ce sujet et ça ne me dérange pas si tu fais le talk. 
Chez CityMeo nous utilisons Apollo Client depuis peu de temps.
(Zélia)

**Comment by ricovitch** [comment]
+1 pour le sujet "you might not need redux"
En rapport, il y à la démarche de l'auteur de "redux-form" qui a créé un nouveau framework "final-form" entre autre pour ne plus passer par redux pour un simple formulaire : https://codeburst.io/final-form-the-road-to-the-checkered-flag-cd9b75c25fe

**Comment by euZebe** [comment]
Va-t-il vraiment y avoir un meetup le 8 mai ? (férié, tout ça...)
S'il est repoussé à la semaine suivante (par exemple), je pense que mon sujet sera prêt.

**Comment by MoOx** [comment]
redux + apollo + un LT "you might not need redux" (je pense qu'un LT suffit mais si vous aimeriez qu'on rentre juste redux+apollo, je pourrais faire ce talk au prochain.
Pour le reste on fera les en suivant?

## Ce qu'on pourrait faire c'est "une issue par propal de talk" et on gère au "thumb up"?

**Comment by mabhub** [comment]
*(Et les sessions #2, #3,… elles-mêmes peuvent bien se gérer avec des Milestones)*

**Comment by MoOx** [comment]
Je vous propose que toutes les personnes qui ont des idées de talk ouvre des tickets (je ferais les miens tout à l'heure tient), et une fois tous les tickets créés, on demandera au gens de vote via des thumbs up :)
