### ISSUE TITLE
C'est qui Reasonml et qu'est ce qu'il fait là?

### ISSUE THREAD

**Issue by MoOx** [MoOx/react-toulouse#6]
Il était une fois JavaScript et paf, Reasonml a fait des chocapics.

Plus sérieusement, je vous propose de faire un petit tour de pourquoi Reasonml, ses origines et ce qu'il sait faire.

**Comment by euZebe** [comment]
Serais-tu prêt à faire ce talk courant  novembre ?

**Comment by MoOx** [comment]
Carrément

**Comment by euZebe** [comment]
Le 22 novembre à Labège ?

**Comment by MoOx** [comment]
Yep!

**Comment by euZebe** [comment]
to be closed :)

**Comment by MoOx** [comment]
Ouais je ferme quand j'aurais mis sur le site les slides & co :)

**Comment by MoOx** [comment]
Closed by d3603643e6c39ba8ecd646af2909c9e844e92a04
