### ISSUE TITLE
Storybook : d'une liste de composants à un Design System

### ISSUE THREAD

**Issue by JulienPradet** [MoOx/react-toulouse#8]
Je propose de faire un talk pour parler de l'utilisation de Storybook pour faire un Design System.

En gros, l'idée serait de référencer les addons utiles (et comment les utiliser) pour que ce ne soit pas juste une interface de dev, mais que ce soit un point central surlequel peut avoir lieu les discussions entre devs, designers, sales, etc.

Liste minimum : knobs, readme, snapshots, liens entre les pages, affichages des tests, internationalisation.
Mais il faut que je replonge dans nos projets pour en faire une liste plus détaillée.

Puis, en fonction du temps, je présenterai comment faire ses propres addons/decorateurs.

Je pense que je resterai sur un format de 30 minutes pour celui là.

**Comment by euZebe** [comment]
Serais-tu prêt à présenter ce talk courant novembre ?

**Comment by JulienPradet** [comment]
Yes, ca devrait le faire. Mi/fin novembre plutôt que début novembre m'arrangerait mieux, mais je dois pouvoir m'arranger dans tous les cas :)

**Comment by euZebe** [comment]
Le 22 novembre à Labège ?

**Comment by JulienPradet** [comment]
Ca marche ! :+1:

**Comment by euZebe** [comment]
20 novembre plutôt.

**Comment by MoOx** [comment]
Closed by d3603643e6c39ba8ecd646af2909c9e844e92a04
