### ISSUE TITLE
Introduction à Apollo Client avec React

### ISSUE THREAD

**Issue by Liliatux** [MoOx/react-toulouse#9]
(Suite à #2)
[GraphQL](https://graphql.org/learn/) faisant de plus en plus parler de lui en ce moment, je vous propose un talk de 15 à 30 minutes pour présenter Apollo Client (client GraphQL) à travers 3 questions:

- Apollo Client qu'est ce que c'est ?
- Comment s'intègre-t-il avec React ?
- Comment fonctionne-il ?

**Comment by euZebe** [comment]
@moox peux-tu fermer cette discussion, le talk ayant eu lieu en juin ? Merci.

**Comment by Liliatux** [comment]
Oui j'avais oublié merci.
